redirects:
  product-features/liquidity-pool: product-features/liquidity-providers/README.md
  product-features/liquidity-pool/self-service-listing: product-features/self-service-listing.md
  how-to/how-to-add-remove-liquidity: product-features/liquidity-providers/how-to.md
  product-features/swap: product-features/token-swaps/README.md
  how-to/swap: product-features/token-swaps/how-to.md