# ⚙️ IMPORTANT: When setting up GitBook GitHub sync, be sure to set the site directory to `./developers/` in the GitBook UI.

root: ./ 
# All other options that specify paths will be relative to this root folder.

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  developers/testnet: developers/networks/testnet.md
  developers/smart-contracts: developers/networks/mainnet.md
  developers/smart-contracts/token-list: developers/networks/mainnet.md
  developers/smart-contracts/amm-pool-mapping: developers/protocol-contracts/README.md