root: ./ 
# All other options that specify paths will be relative to this root folder.

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  product-features/liquidity-pool: ./product-features/liquidity-pools/README.md
  product-features/liquidity-pool/self-service-listing: ./product-features/self-service-listing.md
  how-to/how-to-add-remove-liquidity: ./product-features/liquidity-pools/how-to.md
  product-features/swap: ./product-features/stacks-swaps/README.md
  how-to/swap: ./product-features/stacks-swaps/how-to.md
  product-features/farm: ./product-features/farming/README.md
  product-features/farm/self-service-farming: docs/product-features/self-service-farming.md
  how-to/farm-and-harvest: ./product-features/farming/how-to.md
  product-features/stake: ./product-features/staking/README.md
  how-to/stake-usdalex: ./product-features/staking/README.md